apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: "go-visitors-web-aws"
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      name: http-port
      port: 8080
      targetPort: 3000
